# File: .readthedocs.yaml

version: 2

conda:
  environment: docs/environment.yml

build:
  image: latest
  apt_packages:
    - pandoc

# This part is necessary otherwise the project is not built
python:
  version: 3.7
  install:
    - method: pip
      path: .