# File: .readthedocs.yaml

version: 2

conda:
  environment: docs/environment.yml
  apt_packages:
  - libclang
  - cmake
  - pandoc

build:
  image: latest

# This part is necessary otherwise the project is not built
python:
  version: 3.7
  install:
    - method: pip
      path: .