# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: docs/conf.py

conda:
  environment: conda_env.yml

build:
  image: latest

python:
  version: 3.7
  install:
  - requirements: docs/requirements.txt