# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest
  apt_packages:
    - gdal-bin
    - libgdal-dev

python:
  version: 3.7
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .
    extra_requirements:
      - full