# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: docs/conf.py

conda:
  environment: conda_env.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

python:
  version: 3.7
  install:
  - requirements: docs/requirements.txt
