name: eumap
channels:
  - conda-forge
dependencies:
  - python=3.7
  - affine=2.3
  - bottleneck=1.3
  - gdal=3.1
  - jupyter=1.0.0
  - jupytext=1.11.4
  - numba=0.53
  - numpy=1.19
  - opencv=4.5
  - owslib=0.22
  - pygeos=0.10
  - pyproj=3.1
  - rasterio=1.1
  - pandas=1.1
  - geopandas=0.8
  - shapely=1.7
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - gspread==5.3.2
    - joblib==1.1.0
    - matplotlib==3.4.3
    - minio==7.1.0
    - nbsphinx==0.8.7
    - numpydoc==1.1.0
    - psutil==5.8.0
    - pydata-sphinx-theme==0.6.3
    - pyts==0.11
    - requests==2.24
    - scikit-image==0.17.1
    - scikit-learn==0.24
    - sphinx-autodoc-typehints==1.12.0
    - sphinx-copybutton==0.4.0
    - sphinx==4.1.2
