name: readthedocs
channels:
  - conda-forge
apt_packages:
  - libclang
  - cmake
  - pandoc
dependencies:
  - affine>=2.3
  - Bottleneck>=1.3
  - gdal>=3.1
  - geopandas>=0.8
  - joblib>=0.17
  - matplotlib>=3.3
  - numpy>=1.19
  - opencv_python>=4.5
  - owslib>=0.24
  - pandas>=1.1
  - pqdm>=0.1
  - pygeos>=0.10
  - pyproj>=3.1
  - pyts>=0.11
  - rasterio>=1.1
  - requests>=2.24
  - scikit_image>=0.17
  - scikit_learn>=0.24
  - Shapely>=1.7