name: readthedocs
channels:
  - conda-forge
dependencies:
  - affine>=2.3
  - bottleneck>=1.3
  - gdal>=3.1
  - geopandas>=0.8
  - joblib>=0.17
  - matplotlib>=3.3
  - numpy>=1.19
  - opencv>=4.5
  - owslib>=0.24
  - pandas>=1.1
  - pygeos>=0.10
  - pyproj>=3.1
  - pyts>=0.11
  - rasterio>=1.1
  - requests>=2.24
  - scikit-image>=0.17
  - scikit-learn>=0.24
  - shapely>=1.7
  - sphinx
  - sphinx-rtd-theme
  - pydata-sphinx-theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - nbsphinx
  - jupytext
  - jupyter
  - matplotlib
  - numpydoc